/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        neu: {
          bg: "#e0f2e9",
          surface: "#e0f2e9",
          "shadow-light": "#ffffff",
          "shadow-dark": "#b8d4c6",
          accent: "#10b981",
          "accent-dark": "#059669",
          text: "#2d4a3e",
          "text-secondary": "#5a7d6e",
          "text-muted": "#8aab9e",
          red: "#e74c3c",
          "red-light": "#fdecea",
          amber: "#f59e0b",
          "amber-light": "#fef3c7",
          blue: "#3b82f6",
          "blue-light": "#dbeafe",
        },
        green: {
          50: "#f0fdf4",
          100: "#dcfce7",
          200: "#bbf7d0",
          300: "#86efac",
          400: "#4ade80",
          500: "#22c55e",
          600: "#16a34a",
          700: "#15803d",
          800: "#166534",
          900: "#14532d",
          950: "#052e16",
        },
        eco: {
          primary: "#10b981",
          secondary: "#059669",
          dark: "#064e3b",
          light: "#d1fae5",
        },
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
      },
      boxShadow: {
        "neu-raised": "6px 6px 12px #b8d4c6, -6px -6px 12px #ffffff",
        "neu-raised-sm": "3px 3px 6px #b8d4c6, -3px -3px 6px #ffffff",
        "neu-raised-lg": "10px 10px 20px #b8d4c6, -10px -10px 20px #ffffff",
        "neu-pressed": "inset 3px 3px 6px #b8d4c6, inset -3px -3px 6px #ffffff",
        "neu-pressed-sm": "inset 2px 2px 4px #b8d4c6, inset -2px -2px 4px #ffffff",
        "neu-hover": "8px 8px 16px #b8d4c6, -8px -8px 16px #ffffff",
        "neu-flat": "0 0 0 transparent",
        "neu-concave": "inset 4px 4px 8px #b8d4c6, inset -4px -4px 8px #ffffff",
        "glow-green": "0 0 20px rgb(16 185 129 / 0.2)",
        "glow-green-lg": "0 0 40px rgb(16 185 129 / 0.25)",
        "nav": "0 4px 12px #b8d4c6",
        "float": "8px 8px 20px #b8d4c6, -8px -8px 20px #ffffff",
        "inner-glow": "inset 0 2px 4px 0 rgb(16 185 129 / 0.06)",
        "card": "6px 6px 12px #b8d4c6, -6px -6px 12px #ffffff",
        "card-hover": "8px 8px 16px #b8d4c6, -8px -8px 16px #ffffff",
        "card-active": "10px 10px 20px #b8d4c6, -10px -10px 20px #ffffff",
      },
      animation: {
        "fade-in": "fadeIn 0.5s ease-out forwards",
        "fade-in-up": "fadeInUp 0.5s ease-out forwards",
        "fade-in-down": "fadeInDown 0.3s ease-out forwards",
        "slide-in-right": "slideInRight 0.3s ease-out forwards",
        "scale-in": "scaleIn 0.2s ease-out forwards",
        "pulse-gentle": "pulseGentle 2s ease-in-out infinite",
        "shimmer": "shimmer 2s linear infinite",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        fadeInUp: {
          "0%": { opacity: "0", transform: "translateY(12px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        fadeInDown: {
          "0%": { opacity: "0", transform: "translateY(-8px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        slideInRight: {
          "0%": { opacity: "0", transform: "translateX(12px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
        scaleIn: {
          "0%": { opacity: "0", transform: "scale(0.95)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        pulseGentle: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.7" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic": "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
    },
  },
  plugins: [],
};
